.\"
.\" Copyright (c) 2009 Mike Belopuhov
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 27 2009 $
.Dt ICBD 8
.Os
.Sh NAME
.Nm icbd
.Nd "Internet Citizen's Band protocol daemon"
.Sh SYNOPSIS
.Nm icbd
.Bk -words
.Op Fl 46Cdnv
.Oo
.Fl G Ar group1 Ns Op , Ns Ar ...
.Oc
.Op Fl L Ar prefix
.Op Fl M Ar modtab
.Op Fl S Ar name
.Sm off
.Oo
.Ar addr Op : Ns Ar port
.Ar \ ...
.Oc
.Sm on
.Ek
.Sh DESCRIPTION
.Nm
is an Internet Citizen's Band
.Pq ICB
protocol daemon which allows peoples to chat online.
.Pp
Please refer to the document specified in the
.Sx SEE ALSO
section for more information about the ICB protocol.
.Pp
The options are as follows:
.Bl -tag -width "-G group"
.It Fl 4
Bind to IPv4 addresses only.
.It Fl 6
Bind to IPv6 addresses only.
.It Fl C
Allow users to create groups.
Please note, that everyone creating a new group becomes its moderator.
.It Fl d
Do not daemonize.
If this option is specified,
.Nm
will run in the foreground and log to
.Dv stderr .
.It Fl G Xo
.Ar group1 Ns Op , Ns Ar ...
.Xc
Instruct
.Nm
to create specified groups on startup.
.It Fl L Ar prefix
Enables logging of all public messages in all groups and specifies a
directory inside the chroot that is owned and is writable by the
.Nm
user.
The server will create subdirectories matching those of the group names
and place log files inside one file per month.
.It Fl M Ar modtab
Specifies a moderator table that can be used to restrict users who
can be granted with moderation of any group.
The
.Ar modtab
file contains one nick per line; empty lines and lines starting with
a hash symbol are ignored.
It's located inside the chroot.
Every time a moderator check is performed,
.Nm
checks the modification time of the file and reloads the table if
any changes have taken place since the last call.
.It Fl n
Disable DNS resolver.
.It Fl S Ar name
Set the server's name to
.Ar name .
.It Fl v
Produce more verbose output.
.El
.Pp
A list of addresses and/or ports to bind to is specified after all arguments.
By default,
.Nm
will try to listen on all interfaces using
.Em icb
protocol port number specified in
.Pa /etc/services .
.Sh SEE ALSO
.Rs
.%T ICB Protocol
.%U ftp://ftp.icb.net/pub/icb/src/icbd/Protocol.html
.Re
.Sh AUTHORS
The
.Nm
program was written by Mike Belopuhov.
